EXTENSIONS = {
    'c++': 'cpp',
    'clang': 'cpp',
    'gcc': 'c',
    'py': 'py',
    'javascript': 'js',
    'java': 'java',
    'c#': 'cs',
    'go': 'go',
    'haskell': 'hs',
    'kotlin': 'kt',
    'delphi': 'dpr',
    'pascal': 'pas',
    'perl': 'pl',
    'php': 'php',
    'rust': 'rs',
    'scala': 'sc',
    'node': 'js',
}
